// AUTO-GENERATED from 'Politica de protecție a datelor website_MOD.docx' (official, verbatim).
// Do NOT edit the text — it is the legal privacy policy, reproduced exactly.
// `k`: 'title' | 'h2' (section heading) | 'p' (paragraph / list line).
export interface PrivacyBlock { k: 'title' | 'h2' | 'p'; text: string; }

export const PRIVACY_BLOCKS: PrivacyBlock[] = [
  { k: "title", text: "Politica de protecție a datelor cu caracter personal" },
  { k: "h2", text: "Definiții și termeni" },
  { k: "p", text: "„Date cu caracter personal” sunt orice informații privind o persoană fizică identificată sau identificabilă, (în continuare – persoană vizată), astfel cum este definit în Legea 195/2024 privind protecția datelor cu caracter personal. O persoană fizică este identificabilă atunci când poate fi recunoscută direct sau indirect, în special prin referire la un element de identificare, precum nume, prenume IDNP, date despre comportamentul și metoda ce procurare/achiziționare, precum și unul sau mai multe elemente specifice identității sale fizice, economice, culturale sau sociale." },
  { k: "p", text: "„Prelucrarea datelor cu caracter personal” înseamnă orice operațiune sau serie de operațiuni efectuate asupra datelor cu caracter personal, cu sau fără mijloace automatizate, cum ar fi: colectarea, înregistrarea, automatizarea, stocarea, păstrarea, restabilirea, adaptarea ori modificare, extragerea, consultarea, utilizarea, dezvăluirea prin transmitere, diseminare sau orice alt mod de punere la dispoziție, alăturarea ori combinarea, blocarea, ștergerea sau distrugerea." },
  { k: "p", text: "„Sistemul de evidență a datelor cu caracter personal” este orice serie structurată de date cu caracter personal accesibile conform unor criterii specifice, fie că este centralizată, descentralizată ori repartizată după criterii funcţionale sau geografice." },
  { k: "p", text: "„Operator”, în sensul prezentei Politici, este compania „Crowe Țurcan Mikhailenko” S.R.L. , care stabilește scopurile și mijloacele de prelucrare a datelor cu caracter personal." },
  { k: "p", text: "„Consimțământul subiectului de date cu caracter personal” este manifestarea de voință liberă, specifică, informată și lipsită de ambiguitate a subiectului de date prin care acesta acceptă, printr-o declarație sau printr-o acțiune fără echivoc, ca datele cu caracter personal care îl privesc să fie prelucrate." },
  { k: "p", text: "„Centrul Național Pentru Protecția Datelor cu Caracter Personal (CNPDCP)” este  autoritatea publică independentă instituită în Republica Moldova, competentă în domeniul monitorizării respectării legislației protecției datelor cu caracter personal." },
  { k: "p", text: "Noțiunile și termenii din prezenta Politică ce nu au fost definiți mai sus se vor interpreta în conformitate cu Legea nr. 195/2024 privind protecția datelor cu caracter personal, decât în cazul în care nu le este dată o semnificație distinctă." },
  { k: "h2", text: "Introducere" },
  { k: "p", text: "Prezenta Politică de protecție a datelor cu caracter personal stabilește regulile, principiile și procedurile aplicabile în cadrul companiei „Crowe Țurcan Mikhailenko” S.R.L., privind colectarea, utilizarea, stocarea, transmiterea și protejarea datelor cu caracter personal ale clienților, potențialilor clienți, angajaților, partenerilor și altor persoane care interacționează cu compania și/sau sunt antrenate în relații contractuale, în conformitate cu legislația Republicii Moldova și cu standardele internaționale relevante, inclusiv regulamentul UE 2016/679 (GDPR), în măsura aplicabilă." },
  { k: "h2", text: "Obiective" },
  { k: "p", text: "Stabilirea unui cadru uniform și coerent pentru prelucrarea datelor cu caracter personal în procesele operaționale ale Operatorului;" },
  { k: "p", text: "Asigurarea conformității cu legislația aplicabilă privind protecția datelor cu caracter personal, inclusiv Legea nr. 195/2024 și standardele relevante;" },
  { k: "p", text: "Protejarea drepturilor persoanelor vizate (clienților, vizitatorilor website-ului, partenerilor etc.), precum și a confidențialității, integrității și disponibilității datelor cu caracter personal;" },
  { k: "p", text: "Prevenirea și protecția împotriva riscurilor asociate prelucrării datelor cu caracter personal." },
  { k: "h2", text: "Aplicabilitate" },
  { k: "p", text: "Prezenta Politică se aplică tuturor activităților de prelucrare a datelor cu caracter personal desfășurate de Operator, indiferent de forma sau mediul în care sunt prelucrate datele (electronic, pe suport de hârtie, prin sisteme informatice, prin intermediul platformelor digitale etc.)" },
  { k: "p", text: "Politica se aplică tuturor categoriilor de persoane vizate, inclusiv, dar fără a se limita la: clienți, potențiali clienți, vizitatori ai website-ului și utilizatori ai platformelor online ale Operatorului." },
  { k: "p", text: "Prevederile Politicii sunt obligatorii pentru toate persoanele vizate, pentru colaboratorii Operatorului, pentru persoanele împuternicite, precum și pentru orice persoană care are acces la date cu caracter personal în cadrul relației de muncă, contractuale sau profesionale cu Operatorul." },
  { k: "p", text: "Toate persoanele care prelucrează datele cu caracter personal în numele Operatorului sunt obligate să respecte prezenta Politică și să aplice măsurile tehnice și organizatorice prevăzute de acesta." },
  { k: "h2", text: "Principiile prelucrării datelor cu caracter personal" },
  { k: "p", text: "Prelucrarea datelor în cadrul Operatorului are loc conform următoarelor principii:" },
  { k: "p", text: "Legalitate, echitate și transparență. Operatorul prelucrează datele cu caracter personal în mod legal, echitabil și transparent față de persoana vizată (subiectul datelor cu caracter personal), în conformitate cu Legea nr. 195/2024. Toate operațiunile de prelucrare se bazează pe un temei juridic adecvat și sunt comunicate persoanelor vizate într-o manieră clară și accesibilă." },
  { k: "p", text: "Limitarea scopului. Datele sunt colectate în scopuri determinate, explicite și legitime, specifice activității Operatorului în sectorul prestării serviciilor de consultanță, implementare și suport în domeniul protecției datelor cu caracter personal și nu sunt prelucrare ulterior într-un mod incompatibil cu acte scopuri." },
  { k: "p", text: "Minimizarea datelor colectate. Operatorul se asigură că datele colectate sunt adecvate, relevante și limitate la ceea ce este necesar în raport cu scopurile pentru care sunt prelucrate. Operatorul evită colectarea excesivă și nejustificată de date." },
  { k: "p", text: "Exactitatea datelor. Operatorul ia toate măsurile rezonabile pentru a se asigura că datele cu caracter personal sunt exacte, complete și actualizate. Persoana vizată are dreptul de a solicita rectificarea datelor inexacte sau incomplete." },
  { k: "p", text: "Dreptul la ștergere (dreptul „de a fi uitat”). Persoana vizată are dreptul de a solicita ștergerea datelor sale cu caracter personal în condițiile prevăzute de lege, inclusiv atunci când datele nu mai sunt necesare pentru scopurile pentru care au fost colectate sau când consimțământul a fost retras. Operatorul va examina cerere în termen de 30 zile lucrătoare și va proceda conform obligațiilor sale legale." },
  { k: "p", text: "Limitarea stocării. Datele sunt păstrate într-o formă care permite identificarea persoanelor vizate, doar pentru perioada care nu depășește timpul necesar îndeplinirii scopurilor pentru care sunt colectate, cu respectarea termenilor legali specifici activității Operatorului (ex.: evidență contabilă). După expirarea termenilor aplicabili, datele sunt șterse." },
  { k: "p", text: "Integritate și confidențialitate. Operatorul prelucrează datele într-un mod care asigură securitatea adecvată a acestora, inclusiv protecția împotriva prelucrării neautorizate sau ilegale, pierderii, distrugerii sau deteriorării accidentale, prin implementarea unor măsuri tehnice și organizatorice adecvate nivelului de risc." },
  { k: "p", text: "Responsabilitate. Operatorul este responsabil pentru respectarea principiilor enunțate în prezenta Politică și are obligația de a demonstra conformitatea cu acestea, inclusiv prin documentarea proceselor interne, instruirea personalului, revizuirea periodică a politicilor și menținerea unui registru al operațiunilor de prelucrare." },
  { k: "p", text: "Respectarea drepturilor persoanei vizate. Operatorul aplică toate măsurile necesare pentru a asigura protejarea efectivă a drepturilor persoanelor vizate conform legislației în vigoare, precum și conform GDPR, oferind opțiuni și metode clare și eficiente pentru depunerea solicitărilor." },
  { k: "p", text: "Păstrarea datelor în scop de arhivare și pentru cooperarea cu organele de drept. Operatorul poate păstra anumite date pe termen mai lung atunci când acest lucru este necesar:" },
  { k: "p", text: "pentru îndeplinirea obligațiilor legale privind arhivarea;" },
  { k: "p", text: "pentru demonstrarea și exercitarea drepturilor și intereselor legitime în eventuale litigii;" },
  { k: "p", text: "pentru cooperarea cu organele de drept, autoritățile publice sau instanțele de judecată, atunci când acestea solicită date în temeiuri legale." },
  { k: "p", text: "Această acțiune de păstrare se realizează strict în limitele prevăzute de legislație, doar pentru perioada necesară." },
  { k: "h2", text: "Categorii de date cu caracter personal prelucrate." },
  { k: "p", text: "Operatorul prelucrează datele clienților și/sau potențialilor clienți la accesarea website-ului Operatorului, solicitarea informațiilor despre servicii, transmiterea cererii prin formularele online, contactării prin e-mail sau telefon ori la inițierea unei interacțiuni în scopul obținerii unei oferte, a prestării serviciilor sau a derulării relației contractuale, inclusiv:" },
  { k: "p", text: "date de identificare, email și contact;" },
  { k: "p", text: "date utilizate în scop de marketing," },
  { k: "p", text: "date generate prin utilizarea canalelor digitale: identificatori online, adrese IP, cookie-uri, preferințe;" },
  { k: "p", text: "Operatorul prelucrează date referitoare la funcționarea sistemelor informatice și accesul utilizatorilor:" },
  { k: "p", text: "Log-uri și istoricul acțiunilor în sistemele autorizate;" },
  { k: "p", text: "Date tehnice ale dispozitivelor utilizate;" },
  { k: "p", text: "Date rezultate din procedurile interne de monitorizare a securității." },
  { k: "p", text: "Operatorul utilizează tehnologii automatizate, prin care poate prelucra:" },
  { k: "p", text: "identificatori cookie;" },
  { k: "p", text: "parametri tehnici ai navigării pe website;" },
  { k: "p", text: "date necesare optimizării funcționării platformelor digitale." },
  { k: "h2", text: "Drepturile persoanei vizate:" },
  { k: "p", text: "Dreptul de acces. Persoana are dreptul de a obține confirmarea faptului că datele sale cu caracter personal sunt prelucrate de Operator, precum și dreptul de a primi o copie a datelor prelucrate și informațiile aferente prelucrării. Pentru prima solicitare de acces formulată de către persoana vizată, Operatorul furnizează informațiile și copia datelor cu titlu gratuit. Pentru orice altă solicitare ulterioară, identică sau similară, Operatorul este îndreptățit să perceapă o taxă rezonabilă, calculată în funcție de costurile administrative." },
  { k: "p", text: "Dreptul la rectificare. Persoana vizată are dreptul de a solicita rectificarea datelor cu caracter personal inexacte sau completarea datelor incomplete." },
  { k: "p", text: "Dreptul la ștergere („dreptul de a fi uitat”). Persoana vizată are dreptul de a solicita ștergerea datelor sale cu caracter personal în situațiile prevăzute de lege, inclusiv atunci când:" },
  { k: "p", text: "datele nu mai sunt necesare pentru scopurile pentru care au fost colectate;" },
  { k: "p", text: "persoana vizată își retrage consimțământul și nu există un alt temei juridic pentru prelucrare." },
  { k: "p", text: "Dreptul la opoziție. Persoana vizată are dreptul de a se opune, în orice moment, prelucrării datelor sale personale, inclusiv prelucrării efectuate de către Operator în scopul marketingului direct." },
  { k: "p", text: "Dreptul la restricționarea prelucrării. Persoana vizată are dreptul de a solicita restricționarea prelucrării datelor sale cu caracter personal în cazurile prevăzute de lege, inclusiv atunci când contestă exactitatea datelor sau când prelucrarea este contestată." },
  { k: "p", text: "Dreptul la portabilitatea datelor. Persoana vizată are dreptul de a primi datele sale personale într-un format structurat, precum și de a solicita transmiterea acestora către un alt Operator, în limitele legale." },
  { k: "p", text: "Dreptul de a depune o plângere. Persoana vizată are dreptul de a depune o plângere la autoritatea competentă în cazul în care consideră că prelucrarea datelor sale cu caracter personal încalcă legislația." },
  { k: "p", text: "Dreptul la informare. Persoana vizată are dreptul de a fi informată într-un mod clar și accesibil cu privire la prelucrarea datelor sale cu caracter personal." },
  { k: "p", text: "În vederea exercitării acestor drepturi, persoanele vizate vor completa formularul specializat, elaborat de către Operator și pus la dispoziția persoanelor vizate la solicitare." },
  { k: "h2", text: "Responsabilități." },
  { k: "p", text: "Responsabilitățile Operatorului. Operatorul este responsabil pentru implementarea și respectarea prevederilor prezentei Politici, pentru asigurarea conformității proceselor de prelucrare a datelor cu caracter personal și pentru aplicarea măsurilor tehnice și organizatorice adecvate protecției datelor." },
  { k: "p", text: "Responsabilitățile personalului. Toți angajații Operatorului care, în exercitarea atribuțiilor de serviciu, accesează, utilizează sau prelucrează date cu caracter personal, sunt obligați să respecte prevederile prezentei Politici, instrucțiunile interne, precum și obligațiile de confidențialitate." },
  { k: "p", text: "Accesul autorizat la date. Accesul la datele cu caracter personal este permis exclusiv persoanelor desemnate și autorizate, în limitele competențelor lor funcționale. Orice acces neautorizat este strict interzis și atrage la răspundere disciplinară și, după caz, juridică." },
  { k: "p", text: "Persoanele împuternicite de către Operator sunt obligate să prelucreze datele cu caracter personal exclusiv în limitele instrucțiunilor primite, să aplice măsurile de securitate prevăzute și să respecte obligațiile contractuale privind protecția datelor." },
  { k: "p", text: "Responsabilitatea pentru securitatea sistemelor. Departamentul tehnic și personalul competent sunt responsabili pentru administrarea infrastructurii informatice, menținerea integrității sistemelor de securitate, aplicarea controalelor de acces și implementarea măsurilor tehnice de securitate." },
  { k: "p", text: "Responsabilității în cazul incidentelor de securitate. Orice angajat care constată sau suspectează un incident de securitate privind datele cu caracter personal este obligat să acționeze în conformitate cu Planul de reacție la incidente de securitate elaborat și aprobat de către Operator." },
  { k: "p", text: "Verificarea și monitorizarea conformității. Operatorul poate desfășura controale interne periodice pentru a verifica respectarea prevederilor prezentei Politici și a obligațiilor legale privind protecția datelor cu caracter personal." },
  { k: "h2", text: "Temeiurile juridice ale prelucrării datelor cu caracter personal." },
  { k: "p", text: "Operatorul prelucrează datele cu caracter personal exclusiv în baza unui sau mai multor temeiuri juridice prevăzute de legislație, după cum urmează:" },
  { k: "p", text: "executarea unui contract sau efectuarea demersurilor precontractuale;" },
  { k: "p", text: "îndeplinirea unei obligații legale;" },
  { k: "p", text: "consimțământul persoanei vizate;" },
  { k: "p", text: "interesul legitim al Operatorului" },
  { k: "p", text: "protejarea intereselor persoanei vizate sau a unei alte persoane fizice;" },
  { k: "h2", text: "Scopurile prelucrării datelor cu caracter personal." },
  { k: "p", text: "Operatorul prelucrează datele cu caracter personal exclusiv în scopuri determinate, explicite și legitime, după cum urmează:" },
  { k: "p", text: "executarea relațiilor contractuale cu clienții și/sau potențialii clienți;" },
  { k: "p", text: "comunicarea cu clienții și/sau potențialii clienți și operarea canalelor de suport;" },
  { k: "p", text: "securitatea sistemelor informatice și controlul accesului;" },
  { k: "p", text: "marketing și comunicări comerciale;" },
  { k: "p", text: "îndeplinirea obligațiilor legale ale Operatorului;" },
  { k: "p", text: "prevenirea, identificarea și gestionarea incidentelor;" },
  { k: "p", text: "gestionarea relațiilor cu furnizorii și partenerii contractuali;" },
  { k: "p", text: "protejarea intereselor persoanei vizate." },
  { k: "h2", text: "Perioada de stocare a datelor cu caracter personal." },
  { k: "p", text: "Datele cu caracter personal sunt păstrate doar pentru perioada necesară realizării scopurilor pentru care au fost colectate." },
  { k: "p", text: "Operatorul stabilește următoarele perioade de stocare, în funcție de categoria de date și scopul prelucrării:" },
  { k: "p", text: "date ale angajaților – pe durata raporturilor de muncă, precum și a stagierii, și ulterior, pentru arhivare;" },
  { k: "p", text: "date ale clienților – 5 ani de la ultima interacțiune sau activitate, și ulterior, pentru arhivare;" },
  { k: "p", text: "date contabile și fiscale – conform termenelor obligatorii prevăzute de legislația fiscală și contabilă;" },
  { k: "p", text: "date tehnice și log-uri – pe durata necesară asigurării funcționării și securității sistemelor informatice, cu respectarea termenelor minime și maxime prevăzute de normele aplicabile;" },
  { k: "p", text: "date prelucrate în scop de marketing – până la retragerea consimțământului sau până la exercitarea dreptului de opoziție." },
  { k: "p", text: "La expirarea termenelor de stocare aplicabile, datele sunt supuse procedurii de ștergere, anonimizare, distrugere sau, după caz arhivare, în condițiile stabilite de Operator." },
  { k: "p", text: "Operatorul menține evidența internă a termenelor și procedurilor de stocare și eliminare a datelor, în vederea asigurării respectării principiului limitării păstrării." },
  { k: "h2", text: "Transmiterea transfrontalieră a datelor cu caracter personal." },
  { k: "p", text: "Operatorul poate transfera date cu caracter personal către state membre ale Uniunii Europene sau ale Spațiului Economic European, precum și către alte jurisdicții care asigură un nivel adecvat de protecție, conform listei stabilite de CNPDCP în conformitate cu legislația Republicii Moldova." },
  { k: "p", text: "Transferul de date către un stat terț sau către o organizație internațională se efectuează numai în condițiile existenței unei garanții adecvate privind protecția datelor, inclusiv, după caz:" },
  { k: "p", text: "clauze contractuale standard, aprobate de autoritățile competente;" },
  { k: "p", text: "acorduri sau mecanisme juridice echivalente, care asigură protecția adecvată a datelor;" },
  { k: "p", text: "alte garanții permise expres de lege." },
  { k: "p", text: "Operatorul poate efectua transferuri internaționale de date numai dacă acestea sunt necesare pentru realizarea scopurilor de prelucrare și dacă drepturile persoanei vizate sunt protejate în mod corespunzător." },
  { k: "p", text: "În situația în care transferul se efectuează către state care nu oferă un nivel adecvat de protecție, Operatorul implementează măsuri suplimentare de securitate, menite să asigure confidențialitatea, integritatea și disponibilitatea datelor pe parcursul transferului șu prelucrării ulterioare." },
  { k: "p", text: "Operatorul informează persoana vizată cu privire la transferurile internaționale de date, în condițiile și prin mijloacele prevăzute de lege." },
  { k: "h2", text: "Măsuri tehnice și organizatorice de securitate." },
  { k: "p", text: "Operatorul implementează măsuri tehnice și organizatorice adecvate pentru a asigura un nivel de securitate corespunzător riscurilor asociate prelucrării datelor cu caracter personal, în conformitate cu legislația și cu principiu responsabilității." },
  { k: "p", text: "Măsurile de securitate includ, fără a se limita la:" },
  { k: "p", text: "utilizarea sistemelor de autentificare securizată, parole complexe și, după caz, autentificare cu doi factori (2FA);" },
  { k: "p", text: "gestionarea accesului la date pe baza principiului „necesității de a cunoaște”, în funcție de atribuțiile de serviciu;" },
  { k: "p", text: "limitarea accesului fizic la spațiile în care sunt prelucrate  sau stocate date cu caracter personal;" },
  { k: "p", text: "protejarea echipamentelor, sistemelor informatice și mijloacelor de stocare împotriva accesului neautorizat, deteriorării, pierderii sau furtului;" },
  { k: "p", text: "implementarea și menținerea mecanismelor de jurnalizare (logare) a accesului la sistemele informatice și a acțiunilor efectuate în acestea, după caz, unde este tehnic posibil;" },
  { k: "p", text: "utilizarea soluțiilor de securitate informatică, precum sisteme anti-virus și alte tehnologii relevante;" },
  { k: "p", text: "efectuarea copiilor de rezervă (backup) și asigurarea restaurării datelor în caz de incidente, în conformitate cu procedurile interne;" },
  { k: "p", text: "criptarea datelor, atunci când este necesar și adecvat prelucrării;" },
  { k: "p", text: "asigurarea distrugerii controlate și ireversibile a datelor la expirarea termenelor de stocare sau la necesitate." },
  { k: "p", text: "Operatorul monitorizează în mod continuu nivelul de securitate al sistemelor informatice și adoptă măsuri de prevenire și detectare a accesului neautorizat, a tentativelor de compromitere a infrastructurii sau a oricărui incident de securitate." },
  { k: "p", text: "Persoanele care au acces la date cu caracter personal sunt instruite periodic cu privire la regulile de securitate, obligațiile de confidențialitate și procedurile aplicabile în situația incidentelor." },
  { k: "p", text: "Măsurile tehnice și organizatorice sunt revizuite periodic și actualizate, la necesitate, ori de câte ori este necesar, pentru a reflecta evoluția riscurilor, a tehnologiilor și a cerințelor legale." },
  { k: "h2", text: "Accesul la date și gestionarea riscurilor" },
  { k: "p", text: "Accesul la datele cu caracter personal este permis exclusiv persoanelor desemnate de către Operator, în limita atribuțiilor de serviciu și numai în scopurile prevăzute de prezenta Politică  și de legislația aplicabilă." },
  { k: "p", text: "Accesul se acordă în baza principiului „necesității de a cunoaște” în funcție de atribuțiile de serviciu, astfel încât persoanele autorizate să utilizeze doar datele strict necesare îndeplinirii atribuțiilor funcționale." },
  { k: "p", text: "Operatorul stabilește nivelul de acces pentru fiecare categorie de personal, în funcție de rol, responsabilitate și natura datelor prelucrate." },
  { k: "p", text: "Orice acces la sistemele informatice care conțin date cu caracter personal este supus autentificării prealabile și este monitorizat prin mecanisme de jurnalizare." },
  { k: "p", text: "Persoanele care au acces la datele cu caracter personal sunt obligate să respecte confidențialitatea acestora și să utilizeze datele exclusiv în scopurile pentru care a fost acordat accesul." },
  { k: "p", text: "Operatorul identifică, evaluează și monitorizează riscurile asociate prelucrării datelor cu caracter personal, ținând cont de natura datelor, volumul prelucrării, tehnologiile utilizate și potențialele amenințări și riscuri." },
  { k: "p", text: "Operatorul implementează măsuri adecvate pentru reducerea riscurilor, incluzând controale tehnice, măsuri organizatorice și proceduri interne pentru prevenirea incidentelor de securitate." },
  { k: "p", text: "În situațiile în care prelucrarea datelor poate genera riscuri ridicate pentru drepturile și libertățile persoanei vizate, Operatorul efectuează evaluări ale impactului asupra protecției datelor (DPIA), în conformitate cu legislația în vigoare." },
  { k: "p", text: "Personalul Operatorului este obligat să raporteze imediat orice situație care poate constitui risc, vulnerabilitate sau incident privind protecția datelor cu caracter personal." },
  { k: "p", text: "Operatorul poate efectua controale interne periodice și audituri pentru evaluarea eficacității măsurilor implementate și pentru actualizarea acestora în funcție de evoluția tehnologică și legală." },
  { k: "h2", text: "Prelucrarea datelor prin cookie-uri" },
  { k: "p", text: "Operatorul utilizează cookie-uri și tehnologii similare pe platformele sale online în scopul asigurării funcționării adecvate a site-ului, îmbunătățirii experienței de utilizator, analizării utilizării platformelor și, după caz, furnizării de conținut personalizat." },
  { k: "p", text: "Operatorul poate utiliza următoarele categorii de cookie-uri:" },
  { k: "p", text: "Cookie-uri strict necesare, indispensabile funcționării tehnice a platformei, care permit navigarea și utilizarea funcționării de bază și care nu necesită consimțământul utilizatorului." },
  { k: "p", text: "Cookie-uri funcționale, utilizate pentru personalizarea experienței utilizatorului și pentru memorarea preferințelor acestuia." },
  { k: "p", text: "Cookie-uri de analiză și performanță, utilizate pentru obținerea de date statistice anonimizate privind modul de utilizare a platformei, paginile vizualizate, durata sesiunilor și alte informații relevante pentru optimizarea funcționării serviciilor;" },
  { k: "p", text: "Cookie-uri de marketing și publicitate, utilizate pentru personalizarea conținutului publicitar și pentru analizarea eficacității campaniilor, utilizate doar în baza consimțământului utilizatorului." },
  { k: "p", text: "Cookie-urile sunt utilizate în temeiul interesului legitim al Operatorului de a asigura funcționarea tehnică a platformei." },
  { k: "p", text: "Cookie-urile funcționale, de analiză performanță și marketing se utilizează exclusiv în baza consimțământului utilizatorului, exprimat prin intermediul mecanismelor pe platformă." },
  { k: "p", text: "Utilizatorul poate accepta sau respinge utilizarea cookie-urilor opționale prin bannerul de consimțământ aflat pe platformă sau prin setările browser-ului." },
  { k: "p", text: "Retragerea consimțământului nu afectează legalitatea prelucrării realizate anterior retragerii." },
  { k: "p", text: "Durata de stocare a cookie-urilor variază în funcție de tipul acestora și este determinată de setările tehnice ale platformei." },
  { k: "p", text: "Datele colectate prin cookie-uri pot include identificatori online, adrese IP, preferințe de utilizare, acțiuni pe platformă, pagini accesate și alte informații tehnice similare" },
  { k: "p", text: "Aceste date sunt prelucrate exclusiv în scopurile pentru care cookie-urile au fost implementate și în limitele consimțământului exprimat de utilizator." },
  { k: "h2", text: "Arhivarea și distrugerea datelor" },
  { k: "p", text: "Operatorul arhivează datele cu caracter personal în conformitate cu legislația, cu cerințele interne și cu termenele de păstrare stabilite pentru fiecare categorie de date." },
  { k: "p", text: "Datele arhivate sunt păstrate în condiții care asigură integritatea, confidențialitatea și disponibilitatea acestora, prin aplicarea măsurilor tehnice și organizatorice adecvate." },
  { k: "p", text: "Accesul la datele arhivate este restricționat și permis exclusiv persoanelor autorizate, pe baza competențelor funcționale și responsabilităților specifice." },
  { k: "p", text: "Arhivarea se realizează prin mijloace fizice sau digitale, cu respectarea normelor de securitate aplicabile fiecărui tip de suport." },
  { k: "p", text: "La expirarea termenului de păstrare, sau atunci când datele nu mai sunt necesare pentru scopurile pentru care au fost colectate, Operatorul procedează la distrugerea sau ștergerea acestora, după caz la anonimizare." },
  { k: "p", text: "Distrugerea datelor se realizează astfel încât să prevină orice posibilitate de recuperare, utilizare sau acces neautorizat." },
  { k: "p", text: "Distrugerea datelor pe suport fizic se efectuează prin mijloace mecanice adecvate, care garantează ireversibilitatea procesului." },
  { k: "p", text: "Ștergerea datelor pe suport electronic se efectuează prin proceduri tehnice care asigură eliminarea completă și definitivă a informațiilor din sistemele informatice, inclusiv copiile de rezervă, în măsura în care acest lucru este posibil și compatibil cu obligațiile legale ale Operatorului." },
  { k: "p", text: "Operatorul poate utiliza servicii specializate pentru distrugerea datelor, cu respectarea obligațiilor contractuale privind confidențialitatea și securitatea prelucrării." },
  { k: "p", text: "Operatorul menține evidențe interne privind arhivarea și distrugerea datelor, incluzând data operațiunii, categoria de date, metoda utilizată și persoana responsabilă." },
  { k: "p", text: "Evidențele sunt păstrate conform cerințelor legale și interne privind responsabilitatea și auditul proceselor de prelucrare." },
  { k: "h2", text: "Revizuirea și modificarea Politicii" },
  { k: "p", text: "Prezenta Politică este supusă revizuirii periodice, la intervale stabilite de Operator, în vederea menținerii conformității cu legislația aplicabilă, cu standardele de securitate și cu procesele interne ale Operatorului." },
  { k: "p", text: "Revizuirea Politicii se realizează, de asemenea, ori ce câte ori apar modificări relevante în cadrul legislativ, în structura organizațională, în sistemele informatice sau în procesele de prelucrare a datelor cu caracter personal." },
  { k: "p", text: "Revizuirile sunt documentate și aprobate de către persoanele cu responsabilități desemnate de către Operator." },
  { k: "p", text: "Operatorul poate modifica prezenta Politică în orice moment, în funcție de necesități legale, operaționale sau tehnice." },
  { k: "p", text: "Orice modificare intră în vigoare la data indicată în actul de aprobare." },
  { k: "p", text: "Operatorul asigură comunicarea modificărilor către personal, precum și pune la dispoziția persoanelor vizate versiunea actualizată a Politicii, prin mijloace adecvate stabilite de Operator." },
  { k: "p", text: "Operatorul menține o evidență completă a versiunilor Politicii, inclusiv datele modificărilor și persoanele care au efectuat aprobările." },
  { k: "p", text: "Doar versiunea aprobată și actualizată a Politicii este aplicabilă și obligatorie pentru toate persoanele avute în vedere în domeniul de aplicare al acesteia." },
  { k: "h2", text: "Dispoziții finale" },
  { k: "p", text: "Prezenta Politică este obligatorie pentru toate persoanele care prelucrează datele cu caracter personal în cadrul activităților desfășurate de Operator, indiferent de funcție, poziție sau relație contractuală." },
  { k: "p", text: "Nerespectarea prevederilor Politicii poate atrage măsuri disciplinare, civile, contravenționale sau penale, în funcție de natura și gravitatea încălcării." },
  { k: "p", text: "Politica intră în vigoare la data aprobării oficiale de către Operator." },
  { k: "p", text: "Odată intrată în vigoare, Politica se aplică integral tuturor activităților de prelucrare a datelor cu caracter personal desfășurate de Operator." },
  { k: "p", text: "Operatorul este responsabil pentru implementarea, monitorizarea și aplicarea prezentei Politici." },
  { k: "p", text: "Operatorul cooperează cu autoritățile competente în domeniul protecției datelor cu caracter personal și pune la dispoziție informațiile necesare, în limitele și condițiile prevăzute de lege." },
  { k: "p", text: "În cazul apariției unor neclarități privind interpretarea sau aplicarea prezentei Politici, prevalează dispozițiile legislației aplicabile în material protecției datelor cu caracter personal." },
  { k: "p", text: "Operatorul își rezervă dreptul de a emite instrucțiuni interne suplimentare pentru aplicarea unitară a Politicii." },
  { k: "p", text: "Țurcan Ivan                                                                            (semnătura) ___________________" },
  { k: "p", text: "Administrator „Crowe Țurcan Mikhailenko” S.R.L." },
  { k: "p", text: "Data: 05.03.2026" },
];
