#!/usr/bin/env node
/**
 * Build-time sitemap generator for Bizcheck.md.
 *
 * Tries to fetch the live list of public tests + templates from the backend
 * and writes a populated sitemap.xml to public/. If the backend is unreachable
 * (offline build), falls back to the static skeleton already in public/sitemap.xml.
 *
 * Trigger: prepended to `npm run build` via the build script in package.json.
 *   $ node scripts/generate-sitemap.mjs
 *
 * Configurable via env:
 *   SITEMAP_BASE_URL   default https://bizcheck.md
 *   SITEMAP_API_URL    default http://localhost:4001/api_crowe_bizcheck
 *                      (use full prod URL when running on server: https://bizcheck.md/api_crowe_bizcheck)
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PUBLIC_DIR = resolve(__dirname, '..', 'public');

const SITE = (process.env.SITEMAP_BASE_URL || 'https://bizcheck.md').replace(/\/$/, '');
const API  = (process.env.SITEMAP_API_URL  || '').replace(/\/$/, '');

const TODAY = new Date().toISOString().slice(0, 10);

// Static, always-present URLs.
const staticUrls = [
  { loc: '/',                       changefreq: 'weekly',  priority: '1.0', alternates: ['uk', 'en'] },
  { loc: '/confidentialitate',      changefreq: 'yearly',  priority: '0.4' },
];

async function fetchJson(url) {
  if (!url) return null;
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(8000) });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

async function buildDynamicUrls() {
  if (!API) return [];
  const urls = [];

  const templates = await fetchJson(`${API}/templates/`);
  if (templates?.templates?.length) {
    for (const t of templates.templates) {
      if (t.slug) {
        urls.push({
          loc: `/sablon/${t.slug}`,
          changefreq: 'monthly',
          priority: '0.7',
        });
      }
    }
  }

  const tests = await fetchJson(`${API}/tests`);
  if (tests?.tests?.length) {
    for (const t of tests.tests) {
      if (t.is_active && t.slug) {
        urls.push({
          loc: `/test/${t.slug}`,
          changefreq: 'monthly',
          priority: '0.8',
        });
      }
    }
  }

  return urls;
}

function urlBlock(u) {
  const altLines = (u.alternates || [])
    .map(lang => `    <xhtml:link rel="alternate" hreflang="${lang}" href="${SITE}${u.loc}"/>`)
    .join('\n');
  const xDefault = u.alternates?.length
    ? `\n    <xhtml:link rel="alternate" hreflang="x-default" href="${SITE}${u.loc}"/>`
    : '';
  return [
    '  <url>',
    `    <loc>${SITE}${u.loc}</loc>`,
    `    <lastmod>${TODAY}</lastmod>`,
    `    <changefreq>${u.changefreq}</changefreq>`,
    `    <priority>${u.priority}</priority>`,
    altLines,
    xDefault,
  ].filter(Boolean).join('\n').replace(/\n\s*$/g, '') + '\n  </url>';
}

(async () => {
  const dynamicUrls = await buildDynamicUrls();
  const all = [...staticUrls, ...dynamicUrls];

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<!-- Auto-generated by scripts/generate-sitemap.mjs at build time. ${all.length} URLs. -->`,
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    '        xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    '',
    ...all.map(urlBlock),
    '',
    '</urlset>',
    '',
  ].join('\n');

  writeFileSync(resolve(PUBLIC_DIR, 'sitemap.xml'), xml, 'utf-8');
  console.log(`[sitemap] wrote ${all.length} URLs (${dynamicUrls.length} dynamic from API, ${staticUrls.length} static)`);
})();
